image: "${DOCKER_REG}/ops/ubuntu:18.04"

# SONAR_PROJECT，格式：产品-项目-分支，这里变量是前缀`产品`
# 产品：sec、fin、industry、homepage，如为空，则填充`default`
# DST_DIR: 目标服务器代码目录
variables:
    SONAR_PROJECT: "RealCenter"
    USER_TEST: "root"
    USER_DEV: "root"
    USER_MASTER: "shizhen.xu"

    # DST_HOST_DEV: '106.38.203.236'
    # DST_HOST_DEV_PORT: 36022

    # DST_HOST_TEST_PORT: 10028
    # DST_HOST_TEST: '106.38.203.236'

    # DST_HOST_MASTER: '106.38.203.236'
    # DST_HOST_MASTER_PORT: 10028

    DST_DIR: "/root/realcenter"
    NPM_REG: "https://registry.npm.taobao.org"
    VERSION: "v1.0.2"

# 目前只区分分支：`线上`和`其他`
# `线上`：需要手动执行代码检测
# `其他`：代码提交后，自动执行

before_script:
    - source .gitlab/scripts/utils.sh

stages:
    # 'codeCheck(质量检测)'
    - "buildImage(打包镜像)"
    - "deploy(部署)"
include:
    # local: '.gitlab/ci/job-codecheck-test.yml'
    - local: ".gitlab/ci/job-build-image.yml"
    - local: ".gitlab/ci/job-code-deploy-test.yml"
